# Copyright (c) 2019-2020-2021 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
name: Create and Upload AppImage
on:
  push:
    # branches: ["main", "new-feature-github-actions"]

jobs:
  create-appimage:
    name: Create AppImage
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: Create AppImage (linux)
        run: |          
          export LD_LIBRARY_PATH=${{ github.workspace }}/dist/ubuntu-gcc/usr/lib/:$LD_LIBRARY_PATH
          export OUTPUT=${{ github.workspace }}/build/qtedit4-qt671-x86_64.AppImage
          sudo apt install fuse libxkbcommon-x11-0 libxcb-cursor-dev libxkbcommon-dev

          wget --no-verbose "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage"
          wget --no-verbose "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage"
          chmod +x linuxdeploy*.AppImage

          ./linuxdeploy-x86_64.AppImage --appdir ${{ github.workspace }}/build/ubuntu-gcc/dist/ --plugin qt --output appimage
        working-directory: ${{ github.workspace }}/build/dist
      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: qtedit4-qt671-x86_64.AppImage
          path: ${{ runner.workspace }}/build/qtedit4-qt671-x86_64.AppImage
